### ISSUE TITLE
I'm a dev on a project I never touched.

### ISSUE THREAD

**Issue by vim2meta** [LumiteDubbz/Pixel#15]
Hi there laddy, would appreciate that swift remove from that `Developers` section in the `README`. Many thanks, hugs n kisses.

**Comment by LumiteDubbz** [comment]
@vim2meta Hey, I used your docs and edited them to match my bot so I felt it would be right to add your name to credit you, but sure, I'll remove it :ok_hand:

**Comment by DafsCode** [comment]
Likely cause you made the framework haha.
